name: finance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  provider: ^6.1.2
  cloud_firestore: ^5.5.0
  fl_chart: ^0.69.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/millia.png
    - assets/images/millia2.jpg
    - assets/images/millia3.jpg
