// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2z6qq0fXUUCqutf3vJiB7I3R8SEfidg',
    appId: '1:883511983725:web:02f4bb6a3e3320e2114964',
    messagingSenderId: '883511983725',
    projectId: 'finance-app-64a30',
    authDomain: 'finance-app-64a30.firebaseapp.com',
    storageBucket: 'finance-app-64a30.firebasestorage.app',
    measurementId: 'G-G53TCH7C5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MP4S-n-u96SchQ5hTt2oMJRkUSceHSs',
    appId: '1:883511983725:android:d818dedb9bae06a4114964',
    messagingSenderId: '883511983725',
    projectId: 'finance-app-64a30',
    storageBucket: 'finance-app-64a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmXBfBKoWWX5UnAckisvdVHL8PFlN24pU',
    appId: '1:883511983725:ios:263f5c75196cc49a114964',
    messagingSenderId: '883511983725',
    projectId: 'finance-app-64a30',
    storageBucket: 'finance-app-64a30.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmXBfBKoWWX5UnAckisvdVHL8PFlN24pU',
    appId: '1:883511983725:ios:263f5c75196cc49a114964',
    messagingSenderId: '883511983725',
    projectId: 'finance-app-64a30',
    storageBucket: 'finance-app-64a30.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP2z6qq0fXUUCqutf3vJiB7I3R8SEfidg',
    appId: '1:883511983725:web:6d06b7ea47c928ab114964',
    messagingSenderId: '883511983725',
    projectId: 'finance-app-64a30',
    authDomain: 'finance-app-64a30.firebaseapp.com',
    storageBucket: 'finance-app-64a30.firebasestorage.app',
    measurementId: 'G-W8F4JY4M5C',
  );
}
